#!/bin/bash
# STARalign 0.5.29
# Generated by dx-app-wizard.

main() {

    dx download "$fq1" -o ${pair_id}.trim.R1.fastq.gz
    dx download "$fq2" -o ${pair_id}.trim.R2.fastq.gz
    dx download "$reference" -o rnaref.tar.gz

    mkdir rnaref
    tar -I pigz -xvf rnaref.tar.gz --strip-components=1 -C rnaref

    docker run -v ${PWD}:/data docker.io/goalconsortium/starfusion:0.5.29 -p ${pair_id} -r rnaref -a ${pair_id}.trim.R1.fastq.gz -b ${pair_id}.trim.R2.fastq.gz -f

    tar cf ${pair_id}.starfusion.tar ${pair_id}.*.txt
    gzip ${pair_id}.starfusion.tar
    
    starfusion=$(dx upload ${pair_id}.starfusion.tar.gz --brief)

    dx-jobutil-add-output starfusion "$starfusion" --class=file
}
