#!/bin/bash
# STARalign
# Generated by dx-app-wizard.

main() {

    dx download "$fq1" -o ${sampleid}.trim.R1.fastq.gz
    dx download "$fq2" -o ${sampleid}.trim.R2.fastq.gz
    dx download "$reference" -o rnaref.tar.gz
    dx download "$panel" -o panel.tar.gz
    tar xvfz panel.tar.gz
    
    mkdir CTAT_resource_lib
    docker run -v ${PWD}:/data docker.io/goalconsortium/starfusion:1.0.0 tar -I pigz -xvf rnaref.tar.gz --strip-components=2 -C CTAT_resource_lib

    cp genelist.txt panelgenes.txt
    docker run -v ${PWD}:/data docker.io/goalconsortium/starfusion:1.0.0 bash /seqprg/school/process_scripts/alignment/starfusion.sh -p ${sampleid} -r /data -a ${sampleid}.trim.R1.fastq.gz -b ${sampleid}.trim.R2.fastq.gz -f 
    
    tar cf ${sampleid}.starfusion.tar ${sampleid}*star_fusion/*.tsv *.txt
    gzip ${sampleid}.starfusion.tar
    
    starfusion=$(dx upload ${sampleid}.starfusion.tar.gz --brief)
    dx-jobutil-add-output starfusion "$starfusion" --class=file
}
