#!/bin/bash
# geneabund 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of pair_id: '$pair_id'"
    echo "Value of aligned: '$aligned'"
    echo "Value of stranded: '$stranded'"


    dx download "$aligned" -o sbam
		dx download "$reference" -o reference.tar.gz

		tar xvfz reference.tar.gz

		docker run {JEREMY MAGIC} bash /usr/local/bin/geneabundance.sh -s ${stranded} -g reference/gencode.gtf -p ${pair_id} -b sbam


    counts=$(dx upload counts --brief)
    fpkm=$(dx upload fpkm --brief)


    dx-jobutil-add-output counts "$counts" --class=file
    dx-jobutil-add-output fpkm "$fpkm" --class=file
}
