#!/bin/bash
# bamct_alignQC
# Generated by dx-app-wizard.

main() {

    dx download "$bam" -o ${sampleid}.bam
    dx download "$panel" -o panel.tar.gz
    dx download "$reference" -o ref.tar.gz
    
    tar xvfz panel.tar.gz
    mkdir rnaref
    docker run -v ${PWD}:/data docker.io/goalconsortium/profiling_qc:1.0.0 tar -I pigz -xvf ref.tar.gz --strip-components=1 -C rnaref
    
    docker run -v ${PWD}:/data docker.io/goalconsortium/profiling_qc:1.0.0 samtools index ${sampleid}.bam
    docker run -v ${PWD}:/data docker.io/goalconsortium/profiling_qc:1.0.0 bam-readcount -l targetpanel.bed -w 0 -q 0 -b 25 -f rnaref/genome.fa ${sampleid}.bam > ${sampleid}.bamreadcount.txt
    
    bamreadct=$(dx upload ${sampleid}.bamreadcount.txt --brief)
    dx-jobutil-add-output bamreadct "$bamreadct" --class=file
}
