#!/bin/bash
# align_markdups 0.5.25
# Generated by dx-app-wizard.

main() {

    dx download "$fq1" -o ${pair_id}.trim.R1.fastq.gz
    dx download "$fq2" -o ${pair_id}.trim.R2.fastq.gz
    dx download "$humanref" -o humanref.tar.gz

    mkdir humanref
    tar xvfz humanref.tar.gz --strip-components=1 -C humanref
    alignopt=''
    if [[ ${mdup} == 'fgbio_umi' ]]
    then
	alignopt=" -u"
    fi
    
    docker run -v ${PWD}:/data docker.io/goalconsortium/alignment:0.5.25 bash /seqprg/genomeseer/process_scripts/alignment/dnaseqalign.sh -r humanref -p ${pair_id} -x ${pair_id}.trim.R1.fastq.gz -y ${pair_id}.trim.R2.fastq.gz $alignopt
    docker run -v ${PWD}:/data docker.io/goalconsortium/alignment:0.5.25 bash /seqprg/genomeseer/process_scripts/alignment/markdups.sh -a ${mdup} -b ${pair_id}.bam -p ${pair_id} -r humanref
    
    mv ${pair_id}.dedup.bam ${pair_id}.consensus.bam
    mv ${pair_id}.dedup.bam.bai ${pair_id}.consensus.bam.bai
    
    if [[ -n $virusref ]]
    then
	dx download "$virusref" -o virusref.tar.gz
	mkdir virusref
	tar xvfz virusref.tar.gz --strip-components=1 -C virusref

	docker run -v ${PWD}:/data docker.io/goalconsortium/alignment:0.5.25 bash /seqprg/genomeseer/process_scripts/alignment/virusalign.sh -b ${pair_id}.bam -p ${pair_id} -r virusref -f
	vseqstat=$(dx upload ${pair_id}.viral.seqstats.txt --brief)
	dx-jobutil-add-output vseqstat "$vseqstat" --class=file
    fi

    rawbam=$(dx upload ${pair_id}.bam --brief)
    conbam=$(dx upload ${pair_id}.consensus.bam --brief)
    rawbai=$(dx upload ${pair_id}.bam.bai --brief)
    conbai=$(dx upload ${pair_id}.consensus.bam.bai --brief)
    
    dx-jobutil-add-output rawbam "$rawbam" --class=file
    dx-jobutil-add-output conbam "$conbam" --class=file
    dx-jobutil-add-output rawbai "$rawbai" --class=file
    dx-jobutil-add-output conbai "$conbai" --class=file

}
