#!/bin/bash
# QC_Stats 0.0.1
# Generated by dx-app-wizard.

main() {

    dx download "$Group_BAM" -o group.bam
    dx download "$reference" -o dnaref.tar.gz
    dx download "$panel" -o panel.tar.gz
    dx download "$trimstat" -o ${pair_id}.trimreport.txt
    dx download "$dedupcov" -o ${pair_id}.dedupcov.txt

    tar xvfz dnaref.tar.gz
    tar xvfz panel.tar.gz

    USER=$(dx whoami)

    docker run -v ${PWD}:/data docker.io/goalconsortium/vcfannot:1.0.0 bash /usr/local/bin/bamqc.sh -c targetpanel.bed -n dna -r dnaref -b group.bam -p ${pair_id}
    docker run -v ${PWD}:/data docker.io/goalconsortium/gatk:1.0.0 perl /usr/local/bin/sequenceqc_alignment_withumi.pl -r dnaref -u $USER ${pair_id}.genomecov.txt

    alignstats=$(dx upload ${pair_id}.flagstat.txt --brief)
    meanmap=$(dx upload ${pair_id}.meanmap.txt --brief)
    libcomplex=$(dx upload ${pair_id}.libcomplex.txt --brief)
    insertsize=$(dx upload ${pair_id}.hist.txt --brief)
    alignmentsummarymetrics=$(dx upload ${pair_id}.alignmentsummarymetrics.txt --brief)
    genomecov=$(dx upload ${pair_id}.genomecov.txt --brief)
    covhist=$(dx upload ${pair_id}.covhist.txt --brief)
    lowcapcovstat=$(dx upload ${pair_id}_lowcoverage.txt --brief)
    exoncapcovstat=$(dx upload ${pair_id}_exoncoverage.txt --brief)
    mapqualcov=$(dx upload ${pair_id}.mapqualcov.txt --brief)
    seqstats=$(dx upload ${pair_id}.sequence.stats.txt --brief)

    dx-jobutil-add-output alignstats "$alignstats" --class=file
    dx-jobutil-add-output meanmap "$meanmap" --class=file
    dx-jobutil-add-output libcomplex "$libcomplex" --class=file
    dx-jobutil-add-output insertsize "$insertsize" --class=file
    dx-jobutil-add-output alignmentsummarymetrics "$alignmentsummarymetrics" --class=file
    dx-jobutil-add-output genomecov "$genomecov" --class=file
    dx-jobutil-add-output covhist "$covhist" --class=file
    dx-jobutil-add-output lowcapcovstat "$lowcapcovstat" --class=file
    dx-jobutil-add-output exoncapcovstat "$exoncapcovstat" --class=file
    dx-jobutil-add-output mapqualcov "$mapqualcov" --class=file
    dx-jobutil-add-output seqstats "$seqstats" --class=file
}
