#!/bin/bash
# mutect2 0.0.1
# Generated by dx-app-wizard.

main() {

    dx download "$GATK_Tumor_BAM" -o tumor.bam
    dx download "$reference" -o dnaref.tar.gz

    tar xvfz dnaref.tar.gz

    if [[ ! -z "$GATK_Normal_BAM" ]]
    then
        dx download "$GATK_Normal_BAM" -o normal.bam
    fi

    if [[ ! -z "$pon" ]]
    then
        dx download "$pon" -o pon
        ponopt="-q $pon"
    else
        ponopt=''
    fi

    docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/indexbams.sh
    if [[ -z "$GATK_Normal_BAM" ]]
    then
        docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/germline_vc.sh $ponopt -r dnaref -p ${pair_id} -a mutect2
    else
        docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/somatic_vc.sh $ponopt -r dnaref -p ${pair_id} -x 'tumor' -y 'normal' -n normal.bam -t tumor.bam -a mutect2
    fi
    docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/uni_norm_annot.sh -g 'GRCh38.92' -r dnaref -p ${pair_id}.mutect -v ${pair_id}.mutect.vcf.gz

    mutect_vcf=$(dx upload ${pair_id}.mutect.vcf.gz --brief)

    dx-jobutil-add-output mutect_vcf "$mutect_vcf" --class=file
}
