#!/bin/bash
# Union_VCF
# Generated by dx-app-wizard.

main() {

    echo "Value of vcffiles: '${vcffiles[@]}'"
    echo "Value of caseid: '$caseid'"
    dx download "$genodict" -o genome.dict
    
    for i in ${!vcffiles[@]}
    do
        dx download "${vcffiles[$i]}" -o vcffiles-${i}.tar.gz
	tar xvf vcffiles-${i}.tar.gz
    done

    docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:1.0.0 bash /seqprg/school/process_scripts/variants/union.sh -r ./ -p ${caseid}
    union_vcf=$(dx upload ${caseid}.union.vcf.gz --brief)
    dx-jobutil-add-output union_vcf "$union_vcf" --class=file
}
