#!/bin/bash
# alignqc 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of pair_id: '$pair_id'"
    echo "Value of aligned: '$aligned'"
    echo "Value of alignedsummary: '$alignedsummary'"


    dx download "$aligned" -o bam
    dx download "$alignedsummary" -o alignedsummary
		dx download "$reference" -o reference.tar.gz

		tar xvfz reference.tar.gz


		docker run -v {JEREMY MAGIC} /usr/local/bin/bamqc.sh -p ${pair_id} -b bam -n rna
		docker run -v {JEREMY MAGIC} perl /usr/local/bin/sequenceqc_rnaseq.pl -r reference *flagstat.txt

    fastsqczip=$(dx upload fastsqczip --brief)
    fastqchtml=$(dx upload fastqchtml --brief)
    alignstats=$(dx upload alignstats --brief)


    dx-jobutil-add-output fastsqczip "$fastsqczip" --class=file
    dx-jobutil-add-output fastqchtml "$fastqchtml" --class=file
    dx-jobutil-add-output alignstats "$alignstats" --class=file
}
