#!/bin/bash
# strelka 0.0.1
# Generated by dx-app-wizard.

main() {

    dx download "$Consensus_Tumor_BAM" -o tumor.bam
    dx download "$reference" -o dnaref.tar.gz

    tar xvfz dnaref.tar.gz

    if [[ ! -z $Consensus_Normal_BAM ]]
    then
        dx download "$Consensus_Normal_BAM" -o normal.bam
    fi

    docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/indexbams.sh
    if [[ -z $Consensus_Normal_BAM ]]
    then
        docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/germline_vc.sh -r dnaref -p ${pair_id} -a strelka2
    else
        docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/somatic_vc.sh -r dnaref -p ${pair_id} -x 'tumor' -y 'normal' -n normal.bam -t tumor.bam -a strelka2
    fi
    docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/uni_norm_annot.sh -g 'GRCh38.92' -r dnaref -p ${pair_id}.strelka2 -v ${pair_id}.strelka2.vcf.gz

    strelka2_vcf=$(dx upload ${pair_id}.strelka2.vcf.gz --brief)

    dx-jobutil-add-output strelka2_vcf "$strelka2_vcf" --class=file
}
