#!/bin/bash
# GATK 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    dx download "$Consensus_BAM" -o consensus.bam
    dx download "$ref_file" -o reference.tar.gz

    tar xvfz reference.tar.gz
    gunzip reference/genome.fa.gz

    docker run -v ${PWD}:/data docker.io/goalconsortium/gatk:v1 bash /usr/local/bin/gatkrunner.sh -a gatkbam -b consensus.bam -r reference -p ${pair_id}

    finalbam=$(dx upload ${pair_id}.final.bam --brief)
    finalindex=$(dx upload ${pair_id}.final.bam.bai --brief)

    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    dx-jobutil-add-output finalbam "$finalbam" --class=file
    dx-jobutil-add-output finalindex "$finalindex" --class=file
}
