#!/bin/bash
# hisat2 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    echo "Value of fastq: '$fastq'"
    echo "Value of fastq2: '$fastq2'"
    echo "Value of reference: '$reference'"
    echo "Value of options: '$options'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

    dx download "$fastq" -o fastq.gz

    dx download "$reference" -o reference
    if [ -n "$fastq2" ]
    then
        dx download "$fastq2" -o fastq2.gz
    fi
    
    tar xvfz reference
    
    if [ -n "$fastq2" ]
    then
	echo "/usr/bin/hisat2/hisat2  --no-unal --dta "$options" -x b38 -1 fastq -2 fastq2 -S outsam"
	/usr/bin/hisat2/hisat2  --no-unal --dta "$options" -x b38 -1 fastq.gz -2 fastq2.gz -S outsam
    else 
	echo "/usr/bin/hisat2/hisat2  --no-unal --dta "$options" -x b38 -U fastq -S outsam"
	/usr/bin/hisat2/hisat2  --no-unal --dta "$options" -x b38 -U fastq.gz -S outsam
    fi
    
    /usr/bin/samtools view -b -u -S -o unsortbam outsam
    /usr/bin/samtools sort unsortbam outbam
    mv outbam.bam bamfile
    
    # Fill in your application code here.
    #
    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:
    #
    #   dx-jobutil-report-error "My error message"
    #
    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.

    # The following line(s) use the dx command-line tool to upload your file
    # outputs after you have created them on the local file system.  It assumes
    # that you have used the output field name for the filename for each output,
    # but you can change that behavior to suit your needs.  Run "dx upload -h"
    # to see more options to set metadata.

    bam_filename=$(dx describe --name "${fastq}")
    bam_filename_prefix=${bam_filename%.fastq.gz}
    bamfile=$(dx upload bamfile --destination $bam_filename_prefix.bam --brief)

    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    dx-jobutil-add-output bamfile "$bamfile" --class=file
}
