#!/bin/bash
# align_markdups
# Generated by dx-app-wizard.

main() {

    dx download "$bam" -o ${sampleid}.bam
    dx download "$bai" -o ${sampleid}.bam.bai
    alignopt=''
    if [[ ${mdup} == 'fgbio_umi' ]]
    then
	alignopt=" -u"
    fi
    dx download "$humanref" -o humanref.tar.gz

    mkdir humanref
    docker run -v ${PWD}:/data docker.io/goalconsortium/dna_alignment:1.0.0 tar -I pigz -xvf humanref.tar.gz --strip-components=1 -C humanref
    
    docker run -v ${PWD}:/data docker.io/goalconsortium/dna_alignment:1.0.0 bash /seqprg/school/process_scripts/alignment/markdups.sh -a ${mdup} -b ${sampleid}.bam -p ${sampleid} -r humanref
    
    mv ${sampleid}.dedup.bam ${sampleid}.consensus.bam
    mv ${sampleid}.dedup.bam.bai ${sampleid}.consensus.bam.bai

    dedupbam=$(dx upload ${sampleid}.consensus.bam --brief)
    dedupbai=$(dx upload ${sampleid}.consensus.bam.bai --brief)
    dx-jobutil-add-output dedupbam "$dedupbam" --class=file
    dx-jobutil-add-output dedupbai "$dedupbai" --class=file
}
