#!/bin/bash
# Variant_Calling 0.0.1
# Generated by dx-app-wizard.

main() {

    dx download "$Consensus_Tumor_BAM" -o consensus.tumor.bam
    dx download "$GATK_Tumor_BAM" -o gatk.tumor.bam
    dx download "$reference" -o dnaref.tar.gz

    tar xvfz dnaref.tar.gz

    if [ -n "$Consensus_Normal_BAM" ]
    then
        dx download "$Consensus_Normal_BAM" -o consensus.normal.bam
    fi
    if [ -n "$GATK_Normal_BAM" ]
    then
        dx download "$GATK_Normal_BAM" -o gatk.normal.bam
    fi
    if [ -n "$pon" ]
    then
        dx download "$pon" -o ponfile
        ponopt="-q $ponfile"
    else
        ponopt=""
    fi

    docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/indexbams.sh

    if [[ -z "$Consensus_Normal_BAM" ]]
    then

        if [[ "${algo}" == "mutect" ]]
        then
            docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/germline_vc.sh ${ponopt} -r dnaref -p ${pair_id} -a ${algo}
        else
            docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/germline_vc.sh -r dnaref -p ${pair_id} -a ${algo}
        fi

    else

        if [[ "${algo}" == "freebayes" || "${algo}" == "platypus" ]]
        then
            docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/germline_vc.sh -r dnaref -p ${pair_id} -a ${algo}
        elif [[ "${algo}" == "mutect" ]]
        then
            docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/somatic_vc.sh ${ponopt} -r dnaref -p ${pair_id} -x 'tumor' -y 'normal' -n consensus.normal.bam -t consensus.tumor.bam -a ${algo}
        else
            docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/somatic_vc.sh -r dnaref -p ${pair_id} -x 'tumor' -y 'normal' -n consensus.normal.bam -t consensus.tumor.bam -a ${algo}
        fi

    fi

    docker run -v ${PWD}:/data docker.io/goalconsortium/variantcalling:v1 bash /usr/local/bin/uni_norm_annot.sh -g 'GRCh38.92' -r dnaref -p ${pair_id}.${algo} -v ${pair_id}.${algo}.vcf.gz

    vcf=$(dx upload ${pair_id}.${algo}.vcf.gz --brief)

    dx-jobutil-add-output vcf "$vcf" --class=file
}
