#!/bin/bash
# rnaalign
# Generated by dx-app-wizard.

main() {

    dx download "$fq1" -o ${sampleid}.R1.fastq.gz
    dx download "$fq2" -o ${sampleid}.R2.fastq.gz
    dx download "$reference" -o rnaref.tar.gz

    mkdir rnaref
    docker run -v ${PWD}:/data docker.io/goalconsortium/rna_alignment:1.0.0 tar -I pigz -xvf rnaref.tar.gz --strip-components=1 -C rnaref

    umiopt=""
    if [[ -n ${umi} ]]
    then
	umiopt=" -u"
    fi
    docker run -v ${PWD}:/data docker.io/goalconsortium/rna_alignment:1.0.0 bash /seqprg/school/process_scripts/alignment/rnaseqalign.sh -a ${aligner} -p ${sampleid} -r rnaref -x ${sampleid}.R1.fastq.gz -y ${sampleid}.R2.fastq.gz $umiopt

    bam=$(dx upload ${sampleid}.bam --brief)
    bai=$(dx upload ${sampleid}.bam.bai --brief)
    alignstats=$(dx upload ${sampleid}.alignerout.txt --brief)

    dx-jobutil-add-output bam "$bam" --class=file
    dx-jobutil-add-output bai "$bai" --class=file
    dx-jobutil-add-output alignstats "$alignstats" --class=file
}
