#!/bin/bash
# QC_BAM 0.0.1
# Generated by dx-app-wizard.

main() {

    dx download "$Consensus_BAM" -o consensus.bam
    dx download "$reference" -o dnaref.tar.gz
    dx download "$panel" -o panel.tar.gz

    tar xvfz dnaref.tar.gz
    tar xvfz panel.tar.gz

    docker run -v ${PWD}:/data docker.io/goalconsortium/vcfannot:v1 bash /usr/local/bin/bamqc.sh -c targetpanel.bed -n dna -r dnaref -b consensus.bam -p ${pair_id} -s 1
    mv ${pair_id}.genomecov.txt ${pair_id}.dedupcov.txt
    mv ${pair_id}.covhist.txt ${pair_id}.covuniqhist.txt
    mv ${pair_id}.hist.txt ${pair_id}.uniqhist.txt
    mv ${pair_id}_lowcoverage.txt ${pair_id}_lowcoverageuniq.txt
    mv ${pair_id}_exoncoverage.txt ${pair_id}_exoncoverageuniq.txt

    umihist=$(dx upload ${pair_id}.uniqhist.txt --brief)
    dedupcov=$(dx upload ${pair_id}.dedupcov.txt --brief)
    covuniqhist=$(dx upload ${pair_id}.covuniqhist.txt --brief)
    lowcovuniqstat=$(dx upload ${pair_id}_lowcoverageuniq.txt --brief)
    exoncovuniqstat=$(dx upload ${pair_id}_exoncoverageuniq.txt --brief)

    dx-jobutil-add-output umihist "$umihist" --class=file
    dx-jobutil-add-output dedupcov "$dedupcov" --class=file
    dx-jobutil-add-output covuniqhist "$covuniqhist" --class=file
    dx-jobutil-add-output lowcovuniqstat "$lowcovuniqstat" --class=file
    dx-jobutil-add-output exoncovuniqstat "$exoncovuniqstat" --class=file
}
