#!/bin/bash
# geneabund 0.0.1
# Generated by dx-app-wizard.

main() {

    dx download "$Aligned_BAM" -o aligned.bam
    dx download "$reference" -o dnaref.tar.gz

    tar xvfz reference.tar.gz

    docker run -v ${PWD}:/data docker.io/goalconsortium/ :1.0.0 bash /usr/local/bin/geneabundance.sh -s ${stranded} -g dnaref/gencode.gtf -p ${pair_id} -b aligned.bam
    docker run -v ${PWD}:/data docker.io/goalconsortium/gatk:1.0.0 bash /usr/local/bin/gatkrunner.sh -a gatkbam -b consensus.bam -r dnaref -p ${pair_id}

    counts=$(dx upload ${pair_id}.cts --brief)
    strcts=$(dx upload ${pair_id}_stringtie --brief)
    fpkm=$(dx upload ${pair_id}.fpkm.txt --brief)
    finalbam=$(dx upload ${pair_id}.final.bam --brief)
    finalindex=$(dx upload ${pair_id}.final.bam.bai --brief)

    dx-jobutil-add-output counts "$counts" --class=file
    dx-jobutil-add-output strcts "$strcts" --class=file
    dx-jobutil-add-output fpkm "$fpkm" --class=file
    dx-jobutil-add-output finalbam "$finalbam" --class=file
    dx-jobutil-add-output finalindex "$finalindex" --class=file
}
