#!/bin/bash
# ralign 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of pair_id: '$pair_id'"
    echo "Value of trimread1: '$trimread1'"
    echo "Value of trimread2: '$trimread2'"
    echo "Value of align: '$align'"
    echo "Value of markdups: '$markdups'"


    dx download "$trimread1" -o fq1
    dx download "$trimread2" -o fq2
		dx download "$reference" -o reference.tar.gz

		tar xvfz reference.tar.gz
	
		alignopts=''
		if [[ markdups == 'fgbio_umi' ]]
		then 
			alignopts='-u'
		fi

		docker run -v {JEREMY MAGIC} bash /usr/local/bin/rnaseqalign.sh -a align -p ${pair_id} -r reference -x fq1 -y fq2 $alignopts


    aligned=$(dx upload aligned --brief)
    alignedsummary=$(dx upload alignedsummary --brief)


    dx-jobutil-add-output aligned "$aligned" --class=file
    dx-jobutil-add-output alignedsummary "$alignedsummary" --class=file
}
