#!/bin/bash
# bamct_alignQC
# Generated by dx-app-wizard.

main() {

    dx download "$bam" -o ${sampleid}.bam
    dx download "$alignstats" -o ${sampleid}.alignerout.txt
    dx download "$panel" -o panel.tar.gz

    tar xvfz panel.tar.gz
    
    USER=$(dx whoami)
    docker run -v ${PWD}:/data docker.io/goalconsortium/profiling_qc:1.0.0 bash /seqprg/school/process_scripts/alignment/bamqc.sh -p ${sampleid} -b ${sampleid}.bam -n rna 

    fastqczip=$(dx upload ${sampleid}_fastqc.zip --brief)
    fastqchtml=$(dx upload ${sampleid}_fastqc.html --brief)
    seqstats=$(dx upload ${sampleid}.sequence.stats.txt --brief)

    dx-jobutil-add-output fastqczip "$fastqczip" --class=file
    dx-jobutil-add-output fastqchtml "$fastqchtml" --class=file
    dx-jobutil-add-output seqstats "$seqstats" --class=file
}
