#!/bin/bash
# geneabund
# Generated by dx-app-wizard.

main() {

    dx download "$bam" -o ${sampleid}.bam
    dx download "$reference" -o ref.tar.gz

    mkdir rnaref
    docker run -v ${PWD}:/data docker.io/goalconsortium/profiling_qc:1.0.9 tar -I pigz -xvf ref.tar.gz --no-same-owner --strip-components=1 -C rnaref

    docker run -v ${PWD}:/data docker.io/goalconsortium/rna_gene_abundance:1.0.9 bash /seqprg/process_scripts/genect_rnaseq/exonskipping.sh -g rnaref/gencode.gtf -p ${sampleid} -b ${sbam} -r rnaref

    outfile=$(dx upload ${sampleid}.exonskip.answer.txt --brief)
    dx-jobutil-add-output outfile "$outfile" --class=file
}
